### ISSUE TITLE
[ENHANCEMENT] corrolate the output 'rails' with the prompt template

### ISSUE THREAD

**Issue by jlopatec** [Arize-ai/phoenix#1310]
The following should be added to the templates file for each template in the default templates:

RAG_RELEVANCY_PROMPT_MAP = {True: "correct", False: "incorrect"}

It is then used in the following mapping the base dataset:
df_sample["answer"].map(evals.RAG_RELEVANCY_PROMPT_MAP)

also used for rails below:

Q_and_A_classifications = llm_eval_binary(
    dataframe=df_sample,
    template=template,
    model=model,
    rails= list(evals.RAG_RELEVANCY_PROMPT_MAP.values()) ,
)

Ideally the rails could just take in the dict_map directly eventually:
Q_and_A_classifications = llm_eval_binary(
    dataframe=df_sample,
    template=template,
    model=model,
    rails= evals.RAG_RELEVANCY_PROMPT_MAP.values() ,
)

**Comment by mikeldking** [comment]
The pain that needs to be solved here is that all eval templates a predicated on the output of the function. By nature the prompt and the output should be grouped together and be applied together. The ergonomics of importing the template and the output "rails" along with how they are applied needs to be adjusted so that it is clear how the system works.
