### ISSUE TITLE
[BUG] `run_relevance_evals`' fields `query_column_name` and `document_column_name` cause incorrect `PromptTemplate` variable parsing

### ISSUE THREAD

**Issue by fjcasti1** [Arize-ai/phoenix#1522]
See https://github.com/Arize-ai/phoenix/pull/1520#discussion_r1341827224

**Comment by lou-k** [comment]
@axiomofjoy `run_relevance_eval` contains two arguments:
```
    query_column_name: str = "query",
    document_column_name: str = "reference",
```

Supposedly so you can set the name of the columns that contain your query and reference data.

The bug is that `RAG_RELEVANCY_PROMPT_TEMPLATE_STR` assumes that `query_column_name` and `document_column_name` are kept at their default: `{query}` and `{reference}`.

To repo this bug, just call `run_relevance_eval` with a different column name for `query_column_name` or `document_column_name`

**Comment by axiomofjoy** [comment]
Thanks @lou-k for flagging. This function currently expects that the columns of the dataframe match the variable names in the template. Would it clarify the usage of the function to rename `query_column_name` and `reference_column_name` to `query_variable_name` and `reference_variable_name`?

Open to other suggestions on function signature and behavior. This function is overloaded in terms of its functionality and behavior at the moment since it is also used directly on exported OpenInference trace dataframes.

**Comment by axiomofjoy** [comment]
Our documentation on this method was out of date. I've updated the API docs [here](https://docs.arize.com/phoenix/api/evals#phoenix.experimental.run_relevance_eval).

Closing this issue for now, but we can re-open this issue if the folks still find the function confusing.
