### ISSUE TITLE
[trace] - semantic attributes for retrieval evals

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#1585]
There is a need to co-locate evals under the same `attributes` block as the span itself and there's a need for these to be namespaced under a prefix that let's us break out evals and to compute aggregations on these values.

**Comment by RogerHYang** [comment]
Is it a product requirement to account for evals using semantic attributes? I ask because this approach seems like a departure from the Law of Demeter (LoD), as we’re embarking on building (and publicizing) a system requiring a span to know about its evals. (If I write an essay for school, the grade that I get is not part of the essay, because had I known about the grade, I could have written a different essay.) On the other hand, LoD is only a matter of perspective, and the approach here seems to be taking the point of view that a span equates to a row in a table that can be extended rightward indefinitely, where new columns are to be added as semantic attributes. I'm _not_ saying we need to have a debate over the merits, but just want to clarify which mental model we should be holding going forward.
