### ISSUE TITLE
[ENHANCEMENT] use a refine strategy for contexts that don't fit into the context window

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#1666]
**Is your feature request related to a problem? Please describe.**
Use a refine strategy to keep invoking the LLM witch chunks of the context. See llama_index's approach

```python
DEFAULT_REFINE_TEMPLATE = PromptTemplate(
    "We want to understand if the following query and response is"
    "in line with the context information: \n {query_str}\n"
    "We have provided an existing YES/NO answer: \n {existing_answer}\n"
    "We have the opportunity to refine the existing answer "
    "(only if needed) with some more context below.\n"
    "------------\n"
    "{context_msg}\n"
    "------------\n"
    "If the existing answer was already YES, still answer YES. "
    "If the information is present in the new context, answer YES. "
    "Otherwise answer NO.\n"
)```

**Comment by avirlrma** [comment]
Hi @mikeldking,
I would like to give this one a go, can you please assign me this?

**Comment by mikeldking** [comment]
@avirlrma we are actually actively working on this issue and it's part of our roadmap so I think for this one I'm gonna assign it out to a core contributor. But would love any insight that you may have on this problem! Also thanks so much for being willing to help us out! We have a contributor group that meets every 2 weeks and would love to have any help that you can give.

We typically tag issues with `help wanted` and those are entirely fair game. Thanks again!

**Comment by axiomofjoy** [comment]
@avirlrma We'd love to hear your thoughts if you had concrete ideas implementation-wise.

**Comment by axiomofjoy** [comment]
@jlopatec @mikeldking Do we have any concrete data that motivates the need for a refine strategy? I would be interested in both examples where we're overflowing the current context window. I'd also be curious if we have any benchmark datasets with ground truth relevance labels with particularly long documents so I can run some experiments.

**Comment by mikeldking** [comment]
> @jlopatec @mikeldking Do we have any concrete data that motivates the need for a refine strategy? I would be interested in examples where we're overflowing the current context window. I'd also be curious if we have any benchmark datasets with ground truth relevance labels with particularly long documents so I can run some experiments.

It comes up during summarization evals where the context can be a massive PDF or the application is being used to map over context from various sources

**Comment by axiomofjoy** [comment]
Got it. Summarization makes sense as a use-case, since we will often be evaluating the quality of a summary for a corpus of documents that do not simultaneously fit in the context window.

I have taken a look at the LlamaIndex implementation of `RelevanceEvaluator` that leverages a refine strategy. They are classifying relevance between a query and a set of retrieved documents, not between a query and an individual document. I am not clear why a refine strategy is needed for relevance; assuming that the full set of document fit into the context window during response synthesis, and that we are using a similarly powerful model with a comparable context window for evaluation, the documents should probably still fit into the evaluation model's context window. Maybe the refine strategy is being used in this case so that a model with a smaller context window can be used for evaluation, or because they have found empirically that using the refine strategy actually produces better evaluations. I'll ask the LlamaIndex team.

I'm going to start with the summarization use-case, since we've gotten a customer ask for this and because the utility of the refine strategy is clearer to me.

**Comment by avirlrma** [comment]
Thanks for replying @mikeldking @axiomofjoy. I understand about this one being on your roadmap, will look at the other ones. I do not have any solid ideas regarding implementation, I was just looking around the llama-index codebase on how it's implemented. I will follow @axiomofjoy's PR to understand how you tackle this one.
