### ISSUE TITLE
[BUG] snap_to_rail function fails to parse label if explanation includes the other label

### ISSUE THREAD

**Issue by trevor-laviale-arize** [Arize-ai/phoenix#2404]
**Describe the bug**
When the output of the LLM contains both rails values (see example below), the snap_to_rails function returns `NOT_PARSABLE`. 

```
' label: unrelated, explanation: A more relevant recommendation would likely be XYZ.'
```

**To Reproduce**
1. Try to run snap_to_rails with the above output and using [unrelated, relevant] as the rails. 

**Expected behavior**
When asking for explanations, try to ignore the explanation when snapping to rails. 

**Environment (please complete the following information):**
 - OS: MacOS
 - Notebook Runtime [e.g. Jupyter, Colab] - Jupyter 
 - Browser - chrome
 - Version 3.3.0

**Comment by anticorrelator** [comment]
Resolved with @trevor-laviale-arize offline. This is only a problem when passing a custom template to Claude, due to it's sensitivity to various prompts. The rail snapping logic can be improved by creating a custom `phoenix.evals.ClassificationTemplate` instance with a template-specific label parsing function.

**Comment by smirnp** [comment]
@dosu-bot, how to deal with multiple-labels classification? Any options to customize `snap_to_rail ` function from the outside?
