### ISSUE TITLE
[ENHANCEMENT]Double check that traces are not adding latency

### ISSUE THREAD

**Issue by arizedatngo** [Arize-ai/phoenix#2639]
I will gather more requirements from <redacted> 

Gong - https://us-18983.app.gong.io/call?id=4448054836339757390&highlights=%5B%7B%22type%22%3A%22SHARE%22%2C%22from%22%3A408%2C%22to%22%3A628%7D%5D

Sending Traces to Arize or Phoenix? Arize
BatchSpanProcessor or SimpleSpanProcessor? TBD
Code used to instrument? TBD

Will add more to this ticket as we know more

**Comment by RogerHYang** [comment]
@arizedatngo this issue _may_ be fixed by this [PR](https://github.com/Arize-ai/openinference/pull/302) in the latest release. If it's still an issue, you try printing the run times as shown in this [PR](https://github.com/Arize-ai/openinference/pull/301) and let us know which step is taking a long time.

**Comment by RogerHYang** [comment]
While we haven't bottomed out the latency issue, it was demonstrated that sending traces to Phoenix didn't incur latency. So I'm closing this ticket for now.
