### ISSUE TITLE
[ENHANCEMENT] User awareness in traces

### ISSUE THREAD

**Issue by stdweird** [Arize-ai/phoenix#2705]
We want to give users access to the traces they generate via a webapplication that uses llama-index.

We currently see 2 issues:
a. can we inject certain data in the metadata of the spans? we were thinking eg the username. this would give us also a way to filter all spans/traces of a single user
b. can we get the tracedetail with only the tracedetail? we would give the users a url like `http://.../projects/UHJvabcjdDoy/traces/ebf94c5d736a5e72a47c680b7edefgb6`, and have broad authentication on the the `./projects/../traces` url, assuming that only the user who can guess the traceid (or gets it from our app ;) can see it. right now, this tracedetail url also load the main projects page, and is like a popup rather then a standalone page.

if a can be implemented, an url that would filter spans based on metadata would also be good, so we can filter the spans that the user generated themself.

**Comment by axiomofjoy** [comment]
Hey @stdweird, thanks for the message.

> a. can we inject certain data in the metadata of the spans? we were thinking eg the username. this would give us also a way to filter all spans/traces of a single user

As far as I know, LlamaIndex currently does not allow users to supply metadata as a field on their query engine invocations. We've mentioned this to the LlamaIndex team and can bring it up again.

> b. can we get the tracedetail with only the tracedetail? we would give the users a url like http://.../projects/UHJvabcjdDoy/traces/ebf94c5d736a5e72a47c680b7edefgb6, and have broad authentication on the the ./projects/../traces url, assuming that only the user who can guess the traceid (or gets it from our app ;) can see it. right now, this tracedetail url also load the main projects page, and is like a popup rather then a standalone page.

It sounds like you want the trace details to be their own page rather than a pullover so that you can display the page to your users? Can you clarify what you have in mind in terms of authentication?

> if a can be implemented, an url that would filter spans based on metadata would also be good, so we can filter the spans that the user generated themself.

We have support for metadata and filters in Phoenix. The blocker in this case is in getting the metadata associated with traces produced by LlamaIndex.

**Comment by stdweird** [comment]
hey @axiomofjoy thanks for the feedback
- wrt the metdata: where would this data be injected ideally? i already have a custom simplespanprocessor, where i do something with all spans that pass. is that a good place inject the metadata? (until llama-index provides somethng better built in ofcourse)
- wrt the authentication: that depends what we can work with. i would do the auth handling in an apache proxy, so eg mapping http://myhost/traces/user/abcdef to http://myhost/traces/user/<username via apache rewrite>/abcdef. so phoenix could trust the url to filter on eg user. i could also have apache inject some metadata that phoenix can pick up from the header, and eg http://myhost/traces/user would only respond with the user data from that header value. (but i am no expert, so besides some simple mechanisms i can't propose anything).

**Comment by axiomofjoy** [comment]
Thanks for the reply @stdweird.

> wrt the metdata: where would this data be injected ideally? i already have a custom simplespanprocessor, where i do something with all spans that pass. is that a good place inject the metadata? (until llama-index provides somethng better built in ofcourse)

You can add metadata as a JSON object under the metadata attribute. See the semantic conventions [here](https://github.com/Arize-ai/openinference/blob/main/spec/semantic_conventions.md).

**Comment by axiomofjoy** [comment]
Can you help me understand from a product perspective how your end-users benefit from viewing traces? We typically think of the end-user of Phoenix as the AI application developer (yourself), not the end-user of the AI application (i.e., the person interacting with a chat interface). This sounds like a new use-case.

**Comment by axiomofjoy** [comment]
@stdweird Thanks for the clarification, makes sense. It sounds like what you might be after is incorporating RBAC. I'm unsure if RBAC is on the Phoenix roadmap, since we intend to keep the application as lightweight and easy to set up as possible. @mikeldking Can you provide some detail here?

**Comment by stdweird** [comment]
@axiomofjoy well ofcourse, phoenix with builtin RBAC is what we want ;)

but i understand it's not that (yet?), so something simpler is already more then welcome.

**Comment by mikeldking** [comment]
@stdweird thanks for your use-case. It's an interesting one - we don't have RBAC nor giving access to traces to specific users on our current roadmap and I think it might diverge a bit from our primary end-user as described by Xander so we can't really promise anything on this front.

One possible solution is for you to leverage Phoenix's projecting capabilities. This means that you could enforce restrictions at the load balancer level to segment user traffic by `/projects/xyz` where each project would correspond to a user. Not sure how easy it would be to implement this at the load balancer level but you certainly can try. Phoenix does use GraphQL so you could use it to resolve which project corresponds to which user.

I think otherwise your only solution right now is going to be to fork the project for RBAC.

User-awereness in general will be coming in some capacity and you can definitely add any attributes you may need via OpenTelemetry https://docs.arize.com/phoenix/tracing/how-to-tracing/custom-spans
