### ISSUE TITLE
[persistence] deal with hard cardinality of spans in a time window

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#3003]
connection_from_array fetches all traces within a time window, which in reality is unnecessary to load a page. We could at first just put a limit on this as it's un-realistic the user will scroll through more than N traces /spans via the UI. Then figure out connecting the pagination to PG/SQLite.

**Comment by axiomofjoy** [comment]
The strawberry docs make a mention of pagination with SQLAlchemy for Relay [here](https://strawberry.rocks/docs/guides/relay#convert-the-node-to-its-proper-type-when-resolving-the-connection).

**Comment by axiomofjoy** [comment]
*Proposal:*

The best user experience is going to come from cursor-based pagination, not limit/ offset pagination, since we have a continuous flow of traces and spans coming into the application. If we go with limit/ offset pagination, since new spans are constantly coming in, the user might progress to the next offset and find duplicates spans from previous pages. The problem gets more acute the faster the spans are coming in. There's also a question of efficiency when dealing with large offsets. For this reason, cursor-based pagination is preferable long-term.

Cursor-based pagination seems fairly straightforward to implement in the simple case where there is no filtering or sorting applied to the spans, more complex in the case of sorting but no filtering, and requires some time and thought to support for filtering.

**Persistence M0 (we ship with this)**

- [ ] Implement cursor-based pagination for the simplest case of unsorted, unfiltered data.
- [ ] Ensure there is a max spans limit on `/v1/query_spans`.

**Fast follows**

- [ ] Implement cursor-based pagination for the case of sorted, unfiltered data.
- [ ] Implement cursor-based pagination for filters.
- [ ] Refactor our custom relay implementation to the new `strawberry` implementation (not strictly necessary to get this feature out the door, but a nice to have going forward).

**Comment by RogerHYang** [comment]
found some info [here](https://github.com/vamshiaruru/strawberry_async_sqlalchemy_relay?tab=readme-ov-file#relay) also

**Comment by axiomofjoy** [comment]
> found some info [here](https://github.com/vamshiaruru/strawberry_async_sqlalchemy_relay?tab=readme-ov-file#relay) also

This was very helpful.

**Comment by axiomofjoy** [comment]
> *Persistence M0 (we ship with this)*
> 
> - [ ] Implement cursor-based pagination for the simplest case of unsorted, unfiltered data.
> - [ ] Ensure there is a max spans limit on `/v1/spans` to handle more complex cases.
> 
> *Fast follows*
> 
> - [ ] Implement cursor-based pagination for the case of sorted, unfiltered data.
> - [ ] Implement cursor-based pagination for filters.
> - [ ] Refactor our custom relay implementation to the new `strawberry` implementation (not strictly necessary to get this feature out the door, but a nice to have going forward).

I am aiming for all but the refactor for M0.

**Comment by axiomofjoy** [comment]
There's an interesting contradiction in the [Relay pagination spec](https://relay.dev/graphql/connections.htm). To comply with the spec, you need to support passing all of `before`, `after`, `first`, and `last` at once. They even provide a [pseudo-code algorithm](https://relay.dev/graphql/connections.htm#sec-Pagination-algorithm) that handles all four inputs at once. On the other hand, the spec [also requires](https://relay.dev/graphql/connections.htm#sec-undefined.PageInfo.Fields) that:

- you must return `hasNextPage` as true if a next page exists when using `first / after`
- you must return `hasPreviousPage` as true when a previous page exists when using `before / last`

So if you pass all four arguments, you technically are supposed to check for both next and previous pages. But it's not straightforward to do this efficiently in our case. The spec points out this limitation [here](https://relay.dev/graphql/connections.htm#note-a97ec).

For this reason, I am going to require that exactly one of `after / first` or `before / last` is used, and return a 400 otherwise. I saw that this is what the implementation Roger linked was doing, and makes sense now that I am thinking more about.
