### ISSUE TITLE
[ENHANCEMENT] make it configurable to not show "partial" traces

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#3421]
When using the UI, it can be jarring if you have a deeply nested trace and you keep getting partial trace updates

**Comment by RogerHYang** [comment]
This was a workaround for displaying traces whose root span (i.e. whose parent = null) has not or will never be ingested. Displaying "partial" traces is convenient because we don't have to define exactly what "partial" is. In other words, in order to suppress "partial" traces, we'll need additional tracking logic, e.g. a check on whether two spans from the same trace are both missing their parent spans.

**Comment by mikeldking** [comment]
> This was a workaround for displaying traces whose root span (i.e. whose parent = null) has not or will never be ingested. Displaying "partial" traces is convenient because we don't have to define exactly what "partial" is. In other words, in order to suppress "partial" traces, we'll need additional tracking logic, e.g. a check on whether two spans from the same trace are both missing their parent spans, as well as an additional timer to decide when to release the trace (if the root span never arrives). Setting the timer can be tricker because LLM agents can take a while to run.

Oh I understand the rationale - it's just user feedback and I captured it for us to think of a possible toggle for things like root spans.
