### ISSUE TITLE
[datasets] CSV upload should try to JSON.load the column

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#3466]
If you upload a CSV and the column contains JSON, we should try to parse it so that it's structured.
<img width="1603" alt="Screenshot 2024-06-11 at 10 34 23 AM" src="https://github.com/Arize-ai/phoenix/assets/5640648/fae42dab-41a9-453e-a0bd-278fe4f8b05a">

**Comment by RogerHYang** [comment]
I don't think this is a good idea, for a few reasons.
- People who choose csv is most likely not expected nesting
- If we want to allow nesting, we should choose a better format like jsonl
- It would be much better to find a way to let users communicate their intent, rather then making second-hand guesses.
- Practically speaking, if say the LLM output is JSON string, but some strings are broken, and if i we try to parse them we would end up with an inconsistent dataset where some rows are dictionaries while other are strings (i.e. those that are broken json strings). And what do we do if parsing fails? Do we really know when parsing fails it's because it's a broken json string or because it's never intended to be parsed? Do we reject if some fails and some succeeds, but accept if either all fail or all succeed?
