### ISSUE TITLE
[datasets][bug] deleted examples still show up in the UI

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/phoenix#3485]
Seeding the database with revisions and then deleting them causes the UI to still show the deleted ones.

**Comment by mikeldking** [comment]
<img width="1704" alt="Screenshot 2024-06-12 at 10 51 28 AM" src="https://github.com/Arize-ai/phoenix/assets/5640648/18b941e8-9f7b-4c84-b617-3a5a35f13628">

**Comment by axiomofjoy** [comment]
The issue seems to happen because the different dataset versions are created within the same transaction and therefore have the same timestamp. The UI queries for the latest version by time and happens to get the first version. It passes the first version into the examples resolver and gets both examples since they all existed at that time. It tries to query the node interface, but the node interface does not currently support querying for deleted examples, so it fails.

The workaround for now is to ensure that the versions in the fixtures have increasing time stamps.

**Comment by axiomofjoy** [comment]
Related to https://github.com/Arize-ai/phoenix/pull/3474/files

**Comment by axiomofjoy** [comment]
The issue seems to happen because the different dataset versions are created within the same transaction and therefore have the same timestamp. The UI queries for the latest version by time and happens to get the first version. It passes the first version into the examples resolver and gets both examples since they both existed at that time. It tries to query the node interface, but the node interface does not currently support querying for deleted examples, so the query fails.

The workaround for now is to make the versions have strictly increasing timestamps.
