### ISSUE TITLE
[feature request] Log the same traces to different projects

### ISSUE THREAD

**Issue by Nabeegh-Ahmed** [Arize-ai/phoenix#3645]
**Describe the bug**
Consider you have a trace `t1` and you logged it to a project named `xyz` via `px.Client().log_traces(trace_dataset=trace_ds, project_name="xyz")`. Now for someone reason you log the same trace `t1` (among other traces) in a different project `abc` via `px.Client().log_traces(trace_dataset=trace_ds, project_name="abc")`. The trace `t1` will not appear in `abc` as it is already present in `xyz`. Same for logging evaluations.

**To Reproduce**
1. Log traces to one project
2. Log same traces to another project
3. The project will be created but it will be missing the traces already present

**Expected behavior**
The trace should persist in both session with a good level of autonomy. Let's say I log traces with evaluation results onto one project, and the same traces with different evaluations to another project, it should persist in both projects with their own eval results.

**Environment (please complete the following information):**
 - OS: MacOS
 - Browser: Arc
 - Python: 3.12

**Comment by mikeldking** [comment]
Hi @Nabeegh-Ahmed in the new Phoenix this is actually by design as traces are unique. It helps us track / link them appropriately as immutable entities. I totally understand you'd like different behavior but we don't really plan on relaxing since a lot of your work hinges on keeping them immutable once ingested.

There are some alternative:
1. Share the same project and separate out the evals
1. Change the trace / span ids before you ingest. This would at least let you send them to different projects if you want.
1. If running locally change your `PHOENIX_WORKING_DIR` before you re-ingest. You can have as many phoenix.dbs as you would like locally.

LMK if I can help brainstorm any other workarounds.

**Comment by mikeldking** [comment]
It's worth noting that we are shipping #2017 in the coming weeks. These can be generated from spans but will be mutable and can be duplicated and might suit your needs appropriately.

**Comment by Nabeegh-Ahmed** [comment]
@mikeldking I used the approach of changing the trace/span ids before logging to phoenix. I was able to use it for my requirements. 

I also took a look #2017. I think that will the better more robust solution. Great work with the initiative. I will be sure to contribute. Thanks

Ps. I think it is safe to close this issue.
