### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by bharathiprodapt** [Arize-ai/phoenix#4805]
I have added traces in the Phoenix and i tend to download it but getting Bad Request Error 400
Below is the error i get :

HTTPError: 400 Client Error: Bad Request for url: https://app.phoenix.arize.com/v1/spans

Please help me on this

**Comment by mikeldking** [comment]
@bharathiprodapt thamks for reporting. Will have the hosting team take a look. Cc @exiao @fjcasti1

**Comment by fjcasti1** [comment]
Looking into this @bharathiprodapt , we've made improvements such that you can upload/download and operate on datasets and experiments. Our next goal is to unblock you with spans/traces and evaluations. Will get back to you soon

**Comment by fjcasti1** [comment]
Hi @bharathiprodapt I have tested this and it works for me, can you confirm that the issue persists? Any additional information would be useful in that case. I'm closing the issue since I can make your code work (at least what I could reproduce), feel free to comment and reopen if the problem persists
