### ISSUE TITLE
Support Databricks Notebooks

### ISSUE THREAD

**Issue by amank94** [Arize-ai/phoenix#953]
Wondering if Phoenix support for Databricks is on the roadmap, after hitting a few issues here

**Comment by amank94** [comment]
https://arizeai.slack.com/archives/C04956XU2TS/p1689776713557339

**Comment by mikeldking** [comment]
Hey @amank94 - thanks for your feedback. Due to the IP forwarding rules of different notebook environments, it's pretty common for proxies to be used to satisfy these cases. A few solutions are outlined in our FAQ.

first-class support of remote notebooks requires our static assets to be built and hosted in CDNs most likely so it's probably not something on our immediate readmap. Please let us know if the above workarounds satisfy your case.

**Comment by mikeldking** [comment]
related to #675

**Comment by mikeldking** [comment]
Moving into next sprint

**Comment by mikeldking** [comment]
Notes: Given a notebook at https://dbc-f0b05a54-473d.cloud.databricks.com/?o=1018391329803962#notebook/3547232604874946/command/3922796072781124

tensorboard mounts at: https://dbc-dp-1018391329803962.cloud.databricks.com/driver-proxy/o/1018391329803962/0112-220452-osc8oiar/6007/?darkMode=true
